"Cache" ページを翻訳した
uttk/swr-site pull request #106
Opened 2021-06-22 10:27 UTC by uttk

## 概要

https://swr.vercel.app/ja/advanced/cache

を翻訳しました。

## 注意事項

- 「 Provider 」は、「 プロバイダ 」と訳しました。
- 「 Atomic 」は、そのまま 「 アトミック 」と訳しました。

## Issue

fix #105

2021-06-22 15:15 UTC, shioyang requested changes
いくつかコメントしました。

## Provider

拘るのであれば、`provider` は、`user` と同様に `r` で終わる単語として訳語は `ー` で終わるカタカナがよいです。
- user → ユーザー
- provider → プロバイダー

### 参考
> 注3　英語の語末の‐ｅｒ,‐ｏｒ,‐ａｒなどに当たるものは,原則としてア列の長音とし長音符号「ー」を用いて書き表す。

[文化庁：外来語の表記　留意事項その2(細則的な事項)](https://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/naikaku/gairai/honbun06.html)

↓ ここのサイトが詳しいですね。
[Userはユーザかユーザーか：カタカナによる外来語の表記、特に長音表記について](https://u-site.jp/lecture/notation-of-foreign-words/)

2021-06-22 15:15 UTC, shioyang commented on pages/advanced/cache.ja.md
> +    // `provider` は、実装したキャッシュ。たとえば、 `Map()` など。
ここは `cache implementation` なので「キャッシュの実装」でしょうか。
```suggestion
    // `provider` は、たとえば `Map()` のような、キャッシュの実装です。
```

2021-06-22 23:27 UTC, uttk commented on pages/advanced/cache.ja.md
> +これらは、よりカスタマイズされたストレージをSWRで使用する際の問題を解決するためのもので、キャッシュに直接アクセスできるようになっています。
そうですね、単純な表記ゆれです。ご指摘ありがとうございます！

2021-06-22 23:29 UTC, uttk commented on pages/advanced/cache.ja.md
> +`createCache` によって返された `mutate` 関数の使い方は、[ミューテーション ページ](/docs/mutation) で解説されているグローバル `muate` 関数と同様ですが、特定のキャッシュプロバイダにバインドされています。たとえば、指定されたキャッシュからいくつかのキーを再検証したい場合は、次のようにします：
確かにその方が分かりやすいですね👍

2021-06-22 23:30 UTC, uttk commented on pages/advanced/cache.ja.md
> +    // `provider` は、実装したキャッシュ。たとえば、 `Map()` など。
おお！分かりやすいですね。ご指摘ありがとうございます。

2021-06-23 00:18 UTC, uttk commented
@shioyang 

`provider` を 「プロバイダー」と訳すように修正しました。
問題なければ、reviewのステータスの変更よろしくお願いします🙇‍♂️

2021-06-23 00:22 UTC, shioyang approved these changes
コメントの反映ありがとうございました。

2021-06-23 00:24 UTC, merged